version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aws-sdk
    versions:
    - 2.859.0
    - 2.863.0
    - 2.875.0
    - 2.876.0
    - 2.880.0
    - 2.888.0
    - 2.889.0
    - 2.890.0
    - 2.892.0
    - 2.893.0
    - 2.894.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.37
    - 15.0.0
  - dependency-name: documentation
    versions:
    - 13.2.0
    - 13.2.3
    - 13.2.4
